"""empty message

Revision ID: 839d1f570edd
Revises: b7097627582a
Create Date: 2021-12-14 21:06:40.304007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839d1f570edd'
down_revision = 'b7097627582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('work', sa.String(length=100), nullable=True))
    op.drop_column('teacher', 'works')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('works', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('teacher', 'work')
    # ### end Alembic commands ###
